// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/ads.txt": {
    params: {};
  };
  "/pages/:page": {
    params: {
      "page": string;
    };
  };
  "/:pageSlug": {
    params: {
      "pageSlug": string;
    };
  };
  "/games/:gameSlug": {
    params: {
      "gameSlug": string;
    };
  };
  "/games/:gameSlug/:pageSlug": {
    params: {
      "gameSlug": string;
      "pageSlug": string;
    };
  };
  "/games/:gameSlug/guardian-upgrade-costs": {
    params: {
      "gameSlug": string;
    };
  };
  "/games/:gameSlug/immortal-guardians": {
    params: {
      "gameSlug": string;
    };
  };
  "/games/:gameSlug/flea-guide": {
    params: {
      "gameSlug": string;
    };
  };
  "/games/:gameSlug/page-manager": {
    params: {
      "gameSlug": string;
    };
  };
  "/games/:gameSlug/game-manager": {
    params: {
      "gameSlug": string;
    };
  };
  "/games/:gameSlug/navigation-panel": {
    params: {
      "gameSlug": string;
    };
  };
  "/guardian-upgrade-costs": {
    params: {};
  };
  "/immortal-guardians": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/access-denied": {
    params: {};
  };
  "/page-manager": {
    params: {};
  };
  "/game-manager": {
    params: {};
  };
  "/navigation-panel": {
    params: {};
  };
  "/404": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/ads.txt" | "/pages/:page" | "/:pageSlug" | "/games/:gameSlug" | "/games/:gameSlug/:pageSlug" | "/games/:gameSlug/guardian-upgrade-costs" | "/games/:gameSlug/immortal-guardians" | "/games/:gameSlug/flea-guide" | "/games/:gameSlug/page-manager" | "/games/:gameSlug/game-manager" | "/games/:gameSlug/navigation-panel" | "/guardian-upgrade-costs" | "/immortal-guardians" | "/login" | "/signup" | "/dashboard" | "/access-denied" | "/page-manager" | "/game-manager" | "/navigation-panel" | "/404" | "/*";
  };
  "routes/ads-txt.jsx": {
    id: "routes/ads-txt";
    page: "/ads.txt";
  };
  "routes/old-pages.jsx": {
    id: "routes/old-pages";
    page: "/pages/:page";
  };
  "routes/layout.jsx": {
    id: "main";
    page: "/" | "/:pageSlug" | "/games/:gameSlug" | "/games/:gameSlug/:pageSlug" | "/games/:gameSlug/guardian-upgrade-costs" | "/games/:gameSlug/immortal-guardians" | "/games/:gameSlug/flea-guide" | "/games/:gameSlug/page-manager" | "/games/:gameSlug/game-manager" | "/games/:gameSlug/navigation-panel" | "/guardian-upgrade-costs" | "/immortal-guardians" | "/login" | "/signup" | "/dashboard" | "/access-denied" | "/page-manager" | "/game-manager" | "/navigation-panel" | "/404" | "/*";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/page-slug.jsx": {
    id: "routes/page-slug";
    page: "/:pageSlug";
  };
  "routes/game-layout.jsx": {
    id: "routes/game-layout";
    page: "/games/:gameSlug" | "/games/:gameSlug/:pageSlug" | "/games/:gameSlug/guardian-upgrade-costs" | "/games/:gameSlug/immortal-guardians" | "/games/:gameSlug/flea-guide" | "/games/:gameSlug/page-manager" | "/games/:gameSlug/game-manager" | "/games/:gameSlug/navigation-panel";
  };
  "routes/game-home.jsx": {
    id: "routes/game-home";
    page: "/games/:gameSlug";
  };
  "routes/game-page.jsx": {
    id: "game-page-slug";
    page: "/games/:gameSlug/:pageSlug";
  };
  "routes/guardian-costs.jsx": {
    id: "game-guardian-costs";
    page: "/games/:gameSlug/guardian-upgrade-costs";
  } | {
    id: "top-guardian-costs";
    page: "/guardian-upgrade-costs";
  };
  "routes/immortal-guardians.jsx": {
    id: "game-immortal-guardians";
    page: "/games/:gameSlug/immortal-guardians";
  } | {
    id: "top-immortal-guardians";
    page: "/immortal-guardians";
  };
  "routes/flea-guide.jsx": {
    id: "routes/flea-guide";
    page: "/games/:gameSlug/flea-guide";
  };
  "routes/page-manager.jsx": {
    id: "game-page-manager";
    page: "/games/:gameSlug/page-manager";
  } | {
    id: "top-page-manager";
    page: "/page-manager";
  };
  "routes/game-manager.jsx": {
    id: "game-game-manager";
    page: "/games/:gameSlug/game-manager";
  } | {
    id: "top-game-manager";
    page: "/game-manager";
  };
  "routes/navigation-panel.jsx": {
    id: "game-navigation-panel";
    page: "/games/:gameSlug/navigation-panel";
  } | {
    id: "top-navigation-panel";
    page: "/navigation-panel";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.jsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/access-denied.jsx": {
    id: "routes/access-denied";
    page: "/access-denied";
  };
  "routes/not-found.jsx": {
    id: "not-found-404";
    page: "/404";
  } | {
    id: "not-found-wildcard";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/ads-txt": typeof import("./app/routes/ads-txt.jsx");
  "routes/old-pages": typeof import("./app/routes/old-pages.jsx");
  "main": typeof import("./app/routes/layout.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/page-slug": typeof import("./app/routes/page-slug.jsx");
  "routes/game-layout": typeof import("./app/routes/game-layout.jsx");
  "routes/game-home": typeof import("./app/routes/game-home.jsx");
  "game-page-slug": typeof import("./app/routes/game-page.jsx");
  "game-guardian-costs": typeof import("./app/routes/guardian-costs.jsx");
  "game-immortal-guardians": typeof import("./app/routes/immortal-guardians.jsx");
  "routes/flea-guide": typeof import("./app/routes/flea-guide.jsx");
  "game-page-manager": typeof import("./app/routes/page-manager.jsx");
  "game-game-manager": typeof import("./app/routes/game-manager.jsx");
  "game-navigation-panel": typeof import("./app/routes/navigation-panel.jsx");
  "top-guardian-costs": typeof import("./app/routes/guardian-costs.jsx");
  "top-immortal-guardians": typeof import("./app/routes/immortal-guardians.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/signup": typeof import("./app/routes/signup.jsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.jsx");
  "routes/access-denied": typeof import("./app/routes/access-denied.jsx");
  "top-page-manager": typeof import("./app/routes/page-manager.jsx");
  "top-game-manager": typeof import("./app/routes/game-manager.jsx");
  "top-navigation-panel": typeof import("./app/routes/navigation-panel.jsx");
  "not-found-404": typeof import("./app/routes/not-found.jsx");
  "not-found-wildcard": typeof import("./app/routes/not-found.jsx");
};